// Auto-generated by pack_atlas.py - DO NOT EDIT
// Atlas: characters
// Size: 422x20
// Sprite count: 21

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SpriteMeta {
    pub name: String,
    pub x: u32,
    pub y: u32,
    pub frame_width: u32,
    pub frame_height: u32,
    pub frames: u32,
    pub is_animated: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CharactersAtlas {
    pub size: (u32, u32),
    pub sprites: Vec<SpriteMeta>,
}

pub const CHARACTERS_SPRITES: &str = r#"[
  {
    "name": "assassin_stand",
    "x": 2,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "assassin_walk",
    "x": 22,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "barbarian_stand",
    "x": 42,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "barbarian_stand_east",
    "x": 62,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "barbarian_stand_north",
    "x": 82,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "barbarian_stand_west",
    "x": 102,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "barbarian_walk",
    "x": 122,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "necromancer_stand",
    "x": 142,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "necromancer_walk",
    "x": 162,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "paladin_stand",
    "x": 182,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "paladin_walk",
    "x": 202,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "ranger_stand",
    "x": 222,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "ranger_walk",
    "x": 242,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "sorceress_stand",
    "x": 262,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "sorceress_stand_east",
    "x": 282,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "sorceress_stand_north",
    "x": 302,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "sorceress_stand_west",
    "x": 322,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "sorceress_walk",
    "x": 342,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "sorceress_walk_east",
    "x": 362,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "sorceress_walk_north",
    "x": 382,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "sorceress_walk_west",
    "x": 402,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 1,
    "is_animated": false
  }
]"#;

impl CharactersAtlas {
    pub fn find(&self, name: &str) -> Option<&SpriteMeta> {
        self.sprites.iter().find(|s| s.name == name)
    }
}
