// Auto-generated by pack_atlas.py - DO NOT EDIT
// Atlas: icons
// Size: 418x730
// Sprite count: 105

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SpriteMeta {
    pub name: String,
    pub x: u32,
    pub y: u32,
    pub frame_width: u32,
    pub frame_height: u32,
    pub frames: u32,
    pub is_animated: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IconsAtlas {
    pub size: (u32, u32),
    pub sprites: Vec<SpriteMeta>,
}

pub const ICONS_SPRITES: &str = r#"[
  {
    "name": "arrowDown",
    "x": 2,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "arrowLeft",
    "x": 56,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "arrowRight",
    "x": 110,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "arrowUp",
    "x": 164,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "audioOff",
    "x": 218,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "audioOn",
    "x": 272,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "backward",
    "x": 326,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "barsHorizontal",
    "x": 380,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "barsVertical",
    "x": 434,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "basket",
    "x": 488,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "button1",
    "x": 542,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "button2",
    "x": 596,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "button3",
    "x": 650,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "buttonA",
    "x": 704,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "buttonB",
    "x": 758,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "buttonL",
    "x": 812,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "buttonL1",
    "x": 866,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "buttonL2",
    "x": 920,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "buttonR",
    "x": 974,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "buttonR1",
    "x": 1028,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "buttonR2",
    "x": 1082,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "buttonSelect",
    "x": 1136,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "buttonStart",
    "x": 1190,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "buttonX",
    "x": 1244,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "buttonY",
    "x": 1298,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "cart",
    "x": 1352,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "checkmark",
    "x": 1406,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "contrast",
    "x": 1460,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "cross",
    "x": 1514,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "door",
    "x": 1568,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "down",
    "x": 1622,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "downLeft",
    "x": 1676,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "downRight",
    "x": 1730,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "exclamation",
    "x": 1784,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "exitLeft",
    "x": 1838,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "exitRight",
    "x": 1892,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "export",
    "x": 1946,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "fastForward",
    "x": 2000,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "film",
    "x": 2054,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "forward",
    "x": 2108,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "gamepad",
    "x": 2162,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "gamepad1",
    "x": 2216,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "gamepad2",
    "x": 2270,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "gamepad3",
    "x": 2324,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "gamepad4",
    "x": 2378,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "gear",
    "x": 2432,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "home",
    "x": 2486,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "import",
    "x": 2540,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "information",
    "x": 2594,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "joystick",
    "x": 2648,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "joystickLeft",
    "x": 2702,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "joystickRight",
    "x": 2756,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "joystickUp",
    "x": 2810,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "larger",
    "x": 2864,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "leaderboardsComplex",
    "x": 2918,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "leaderboardsSimple",
    "x": 2972,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "locked",
    "x": 3026,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "massiveMultiplayer",
    "x": 3080,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "medal1",
    "x": 3134,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "medal2",
    "x": 3188,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "menuGrid",
    "x": 3242,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "menuList",
    "x": 3296,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "minus",
    "x": 3350,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "mouse",
    "x": 3404,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "multiplayer",
    "x": 3458,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "musicOff",
    "x": 3512,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "musicOn",
    "x": 3566,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "next",
    "x": 3620,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "open",
    "x": 3674,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "pause",
    "x": 3728,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "phone",
    "x": 3782,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "plus",
    "x": 3836,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "power",
    "x": 3890,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "previous",
    "x": 3944,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "question",
    "x": 3998,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "return",
    "x": 4052,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "rewind",
    "x": 4106,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "save",
    "x": 4160,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "scrollHorizontal",
    "x": 4214,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "scrollVertical",
    "x": 4268,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "share1",
    "x": 4322,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "share2",
    "x": 4376,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "signal1",
    "x": 4430,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "signal2",
    "x": 4484,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "signal3",
    "x": 4538,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "singleplayer",
    "x": 4592,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "smaller",
    "x": 4646,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "star",
    "x": 4700,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "stop",
    "x": 4754,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "tablet",
    "x": 4808,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "target",
    "x": 4862,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "trashcan",
    "x": 4916,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "trashcanOpen",
    "x": 4970,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "trophy",
    "x": 5024,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "unlocked",
    "x": 5078,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "up",
    "x": 5132,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "upLeft",
    "x": 5186,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "upRight",
    "x": 5240,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "video",
    "x": 5294,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "warning",
    "x": 5348,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "wrench",
    "x": 5402,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "zoom",
    "x": 5456,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "zoomDefault",
    "x": 5510,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "zoomIn",
    "x": 5564,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "zoomOut",
    "x": 5618,
    "y": 2,
    "frame_width": 50,
    "frame_height": 50,
    "frames": 1,
    "is_animated": false
  }
]"#;

impl IconsAtlas {
    pub fn find(&self, name: &str) -> Option<&SpriteMeta> {
        self.sprites.iter().find(|s| s.name == name)
    }
}
