// Auto-generated by pack_atlas.py - DO NOT EDIT
// Atlas: monsters
// Size: 722x36
// Sprite count: 20

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SpriteMeta {
    pub name: String,
    pub x: u32,
    pub y: u32,
    pub frame_width: u32,
    pub frame_height: u32,
    pub frames: u32,
    pub is_animated: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MonstersAtlas {
    pub size: (u32, u32),
    pub sprites: Vec<SpriteMeta>,
}

pub const MONSTERS_SPRITES: &str = r#"[
  {
    "name": "bat",
    "x": 2,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "bat_0",
    "x": 38,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "bat_1",
    "x": 74,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "bee_0",
    "x": 110,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "bee_1",
    "x": 146,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "eyeball_0",
    "x": 182,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "eyeball_1",
    "x": 218,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "ghost_0",
    "x": 254,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "ghost_1",
    "x": 290,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "pumpking_0",
    "x": 326,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "pumpking_1",
    "x": 362,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "slime",
    "x": 398,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "slime_0",
    "x": 434,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "slime_1",
    "x": 470,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "small_worm",
    "x": 506,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "small_worm_0",
    "x": 542,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "small_worm_1",
    "x": 578,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "worm",
    "x": 614,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "worm_0",
    "x": 650,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "worm_1",
    "x": 686,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  }
]"#;

impl MonstersAtlas {
    pub fn find(&self, name: &str) -> Option<&SpriteMeta> {
        self.sprites.iter().find(|s| s.name == name)
    }
}
