// Auto-generated by pack_atlas.py - DO NOT EDIT
// Atlas: particles
// Size: 596x728
// Sprite count: 96

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SpriteMeta {
    pub name: String,
    pub x: u32,
    pub y: u32,
    pub frame_width: u32,
    pub frame_height: u32,
    pub frames: u32,
    pub is_animated: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ParticlesAtlas {
    pub size: (u32, u32),
    pub sprites: Vec<SpriteMeta>,
}

pub const PARTICLES_SPRITES: &str = r#"[
  {
    "name": "circle_01",
    "x": 2,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "circle_02",
    "x": 70,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "circle_03",
    "x": 138,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "circle_04",
    "x": 206,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "circle_05",
    "x": 274,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "dirt_01",
    "x": 342,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "dirt_02",
    "x": 410,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "dirt_03",
    "x": 478,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "fire_01",
    "x": 546,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "fire_02",
    "x": 614,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "flame_01",
    "x": 682,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "flame_02",
    "x": 750,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "flame_03",
    "x": 818,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "flame_04",
    "x": 886,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "flame_05",
    "x": 954,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "flame_05_rotated",
    "x": 1022,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "flame_06",
    "x": 1090,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "flame_06_rotated",
    "x": 1158,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "flare_01",
    "x": 1226,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "light_01",
    "x": 1294,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "light_02",
    "x": 1362,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "light_03",
    "x": 1430,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "magic_01",
    "x": 1498,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "magic_02",
    "x": 1566,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "magic_03",
    "x": 1634,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "magic_04",
    "x": 1702,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "magic_05",
    "x": 1770,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "muzzle_01",
    "x": 1838,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "muzzle_01_rotated",
    "x": 1906,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "muzzle_02",
    "x": 1974,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "muzzle_02_rotated",
    "x": 2042,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "muzzle_03",
    "x": 2110,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "muzzle_03_rotated",
    "x": 2178,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "muzzle_04",
    "x": 2246,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "muzzle_04_rotated",
    "x": 2314,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "muzzle_05",
    "x": 2382,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "muzzle_05_rotated",
    "x": 2450,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "scorch_01",
    "x": 2518,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "scorch_02",
    "x": 2586,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "scorch_03",
    "x": 2654,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "scratch_01",
    "x": 2722,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "slash_01",
    "x": 2790,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "slash_02",
    "x": 2858,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "slash_03",
    "x": 2926,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "slash_04",
    "x": 2994,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "smoke_01",
    "x": 3062,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "smoke_02",
    "x": 3130,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "smoke_03",
    "x": 3198,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "smoke_04",
    "x": 3266,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "smoke_05",
    "x": 3334,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "smoke_06",
    "x": 3402,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "smoke_07",
    "x": 3470,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "smoke_08",
    "x": 3538,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "smoke_09",
    "x": 3606,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "smoke_10",
    "x": 3674,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "spark_01",
    "x": 3742,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "spark_02",
    "x": 3810,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "spark_03",
    "x": 3878,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "spark_04",
    "x": 3946,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "spark_05",
    "x": 4014,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "spark_05_rotated",
    "x": 4082,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "spark_06",
    "x": 4150,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "spark_06_rotated",
    "x": 4218,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "spark_07",
    "x": 4286,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "star_01",
    "x": 4354,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "star_02",
    "x": 4422,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "star_03",
    "x": 4490,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "star_04",
    "x": 4558,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "star_05",
    "x": 4626,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "star_06",
    "x": 4694,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "star_07",
    "x": 4762,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "star_08",
    "x": 4830,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "star_09",
    "x": 4898,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "symbol_01",
    "x": 4966,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "symbol_02",
    "x": 5034,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "trace_01",
    "x": 5102,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "trace_01_rotated",
    "x": 5170,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "trace_02",
    "x": 5238,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "trace_02_rotated",
    "x": 5306,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "trace_03",
    "x": 5374,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "trace_03_rotated",
    "x": 5442,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "trace_04",
    "x": 5510,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "trace_04_rotated",
    "x": 5578,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "trace_05",
    "x": 5646,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "trace_05_rotated",
    "x": 5714,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "trace_06",
    "x": 5782,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "trace_06_rotated",
    "x": 5850,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "trace_07",
    "x": 5918,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "trace_07_rotated",
    "x": 5986,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "twirl_01",
    "x": 6054,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "twirl_02",
    "x": 6122,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "twirl_03",
    "x": 6190,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "window_01",
    "x": 6258,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "window_02",
    "x": 6326,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "window_03",
    "x": 6394,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "window_04",
    "x": 6462,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  }
]"#;

impl ParticlesAtlas {
    pub fn find(&self, name: &str) -> Option<&SpriteMeta> {
        self.sprites.iter().find(|s| s.name == name)
    }
}
