// Auto-generated by pack_atlas.py - DO NOT EDIT
// Atlas: ui
// Size: 1360x1178
// Sprite count: 82

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SpriteMeta {
    pub name: String,
    pub x: u32,
    pub y: u32,
    pub frame_width: u32,
    pub frame_height: u32,
    pub frames: u32,
    pub is_animated: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UiAtlas {
    pub size: (u32, u32),
    pub sprites: Vec<SpriteMeta>,
}

pub const UI_SPRITES: &str = r#"[
  {
    "name": "arrow_basic_e",
    "x": 2,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "arrow_basic_e_small",
    "x": 38,
    "y": 2,
    "frame_width": 24,
    "frame_height": 24,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "arrow_basic_n",
    "x": 66,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "arrow_basic_n_small",
    "x": 102,
    "y": 2,
    "frame_width": 24,
    "frame_height": 24,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "arrow_basic_s",
    "x": 130,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "arrow_basic_s_small",
    "x": 166,
    "y": 2,
    "frame_width": 24,
    "frame_height": 24,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "arrow_basic_w",
    "x": 194,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "arrow_basic_w_small",
    "x": 230,
    "y": 2,
    "frame_width": 24,
    "frame_height": 24,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "arrow_decorative_e",
    "x": 258,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "arrow_decorative_e_small",
    "x": 294,
    "y": 2,
    "frame_width": 24,
    "frame_height": 24,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "arrow_decorative_n",
    "x": 322,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "arrow_decorative_n_small",
    "x": 358,
    "y": 2,
    "frame_width": 24,
    "frame_height": 24,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "arrow_decorative_s",
    "x": 386,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "arrow_decorative_s_small",
    "x": 422,
    "y": 2,
    "frame_width": 24,
    "frame_height": 24,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "arrow_decorative_w",
    "x": 450,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "arrow_decorative_w_small",
    "x": 486,
    "y": 2,
    "frame_width": 24,
    "frame_height": 24,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "button_rectangle_border",
    "x": 514,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 3,
    "is_animated": true
  },
  {
    "name": "button_rectangle_depth_border",
    "x": 710,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 3,
    "is_animated": true
  },
  {
    "name": "button_rectangle_depth_flat",
    "x": 906,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 3,
    "is_animated": true
  },
  {
    "name": "button_rectangle_depth_gloss",
    "x": 1102,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 3,
    "is_animated": true
  },
  {
    "name": "button_rectangle_depth_gradient",
    "x": 1298,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 3,
    "is_animated": true
  },
  {
    "name": "button_rectangle_depth_line",
    "x": 1494,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 3,
    "is_animated": true
  },
  {
    "name": "button_rectangle_flat",
    "x": 1690,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 3,
    "is_animated": true
  },
  {
    "name": "button_rectangle_gloss",
    "x": 1886,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 3,
    "is_animated": true
  },
  {
    "name": "button_rectangle_gradient",
    "x": 2082,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 3,
    "is_animated": true
  },
  {
    "name": "button_rectangle_line",
    "x": 2278,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 3,
    "is_animated": true
  },
  {
    "name": "button_round_border",
    "x": 2474,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "button_round_depth_border",
    "x": 2542,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "button_round_depth_flat",
    "x": 2610,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "button_round_depth_gloss",
    "x": 2678,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "button_round_depth_gradient",
    "x": 2746,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "button_round_depth_line",
    "x": 2814,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "button_round_flat",
    "x": 2882,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "button_round_gloss",
    "x": 2950,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "button_round_gradient",
    "x": 3018,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "button_round_line",
    "x": 3086,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "button_square_border",
    "x": 3154,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "button_square_depth_border",
    "x": 3222,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "button_square_depth_flat",
    "x": 3290,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "button_square_depth_gloss",
    "x": 3358,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "button_square_depth_gradient",
    "x": 3426,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "button_square_depth_line",
    "x": 3494,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "button_square_flat",
    "x": 3562,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "button_square_gloss",
    "x": 3630,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "button_square_gradient",
    "x": 3698,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "button_square_line",
    "x": 3766,
    "y": 2,
    "frame_width": 64,
    "frame_height": 64,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "check_round_color",
    "x": 3834,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "check_round_grey",
    "x": 3870,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "check_round_grey_circle",
    "x": 3906,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "check_round_round_circle",
    "x": 3942,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "check_square_color",
    "x": 3978,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "check_square_color_checkmark",
    "x": 4014,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "check_square_color_cross",
    "x": 4050,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "check_square_color_square",
    "x": 4086,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "check_square_grey",
    "x": 4122,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "check_square_grey_checkmark",
    "x": 4158,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "check_square_grey_cross",
    "x": 4194,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "check_square_grey_square",
    "x": 4230,
    "y": 2,
    "frame_width": 32,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "icon_checkmark",
    "x": 4266,
    "y": 2,
    "frame_width": 20,
    "frame_height": 18,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "icon_circle",
    "x": 4290,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "icon_cross",
    "x": 4310,
    "y": 2,
    "frame_width": 18,
    "frame_height": 18,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "icon_outline_checkmark",
    "x": 4332,
    "y": 2,
    "frame_width": 20,
    "frame_height": 18,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "icon_outline_circle",
    "x": 4356,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "icon_outline_cross",
    "x": 4376,
    "y": 2,
    "frame_width": 18,
    "frame_height": 18,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "icon_outline_square",
    "x": 4398,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "icon_square",
    "x": 4418,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "slide_hangle",
    "x": 4438,
    "y": 2,
    "frame_width": 24,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "slide_horizontal_color",
    "x": 4466,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 6,
    "is_animated": true
  },
  {
    "name": "slide_horizontal_color_section",
    "x": 4566,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "slide_horizontal_color_section_wide",
    "x": 4586,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 2,
    "is_animated": true
  },
  {
    "name": "slide_horizontal_grey",
    "x": 4622,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 6,
    "is_animated": true
  },
  {
    "name": "slide_horizontal_grey_section",
    "x": 4722,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "slide_horizontal_grey_section_wide",
    "x": 4742,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 2,
    "is_animated": true
  },
  {
    "name": "slide_vertical_color",
    "x": 4778,
    "y": 2,
    "frame_width": 16,
    "frame_height": 96,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "slide_vertical_color_section",
    "x": 4798,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "slide_vertical_color_section_wide",
    "x": 4818,
    "y": 2,
    "frame_width": 16,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "slide_vertical_grey",
    "x": 4838,
    "y": 2,
    "frame_width": 16,
    "frame_height": 96,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "slide_vertical_grey_section",
    "x": 4858,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "slide_vertical_grey_section_wide",
    "x": 4878,
    "y": 2,
    "frame_width": 16,
    "frame_height": 32,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "star",
    "x": 4898,
    "y": 2,
    "frame_width": 64,
    "frame_height": 60,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "star_outline",
    "x": 4966,
    "y": 2,
    "frame_width": 64,
    "frame_height": 60,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "star_outline_depth",
    "x": 5034,
    "y": 2,
    "frame_width": 64,
    "frame_height": 60,
    "frames": 1,
    "is_animated": false
  }
]"#;

impl UiAtlas {
    pub fn find(&self, name: &str) -> Option<&SpriteMeta> {
        self.sprites.iter().find(|s| s.name == name)
    }
}
