// Auto-generated by pack_atlas.py - DO NOT EDIT
// Atlas: world
// Size: 82x20
// Sprite count: 4

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SpriteMeta {
    pub name: String,
    pub x: u32,
    pub y: u32,
    pub frame_width: u32,
    pub frame_height: u32,
    pub frames: u32,
    pub is_animated: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorldAtlas {
    pub size: (u32, u32),
    pub sprites: Vec<SpriteMeta>,
}

pub const WORLD_SPRITES: &str = r#"[
  {
    "name": "floor",
    "x": 2,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "grass",
    "x": 22,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "wall",
    "x": 42,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "wall_alt",
    "x": 62,
    "y": 2,
    "frame_width": 16,
    "frame_height": 16,
    "frames": 1,
    "is_animated": false
  }
]"#;

impl WorldAtlas {
    pub fn find(&self, name: &str) -> Option<&SpriteMeta> {
        self.sprites.iter().find(|s| s.name == name)
    }
}
