// Auto-generated by pack_atlas.py - DO NOT EDIT
// Atlas: world
// Size: 2610x388
// Sprite count: 12

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SpriteMeta {
    pub name: String,
    pub x: u32,
    pub y: u32,
    pub frame_width: u32,
    pub frame_height: u32,
    pub frames: u32,
    pub is_animated: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorldAtlas {
    pub size: (u32, u32),
    pub sprites: Vec<SpriteMeta>,
}

pub const WORLD_SPRITES: &str = r#"[
  {
    "name": "decor_desert",
    "x": 2,
    "y": 2,
    "frame_width": 128,
    "frame_height": 128,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "decor_forest",
    "x": 134,
    "y": 2,
    "frame_width": 128,
    "frame_height": 128,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "decor_ruin",
    "x": 266,
    "y": 2,
    "frame_width": 128,
    "frame_height": 128,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "decor_void",
    "x": 398,
    "y": 2,
    "frame_width": 128,
    "frame_height": 128,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "floor_desert_full",
    "x": 530,
    "y": 2,
    "frame_width": 384,
    "frame_height": 384,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "floor_forest_full",
    "x": 918,
    "y": 2,
    "frame_width": 384,
    "frame_height": 384,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "floor_ruin_full",
    "x": 1306,
    "y": 2,
    "frame_width": 384,
    "frame_height": 384,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "floor_void_full",
    "x": 1694,
    "y": 2,
    "frame_width": 384,
    "frame_height": 384,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "wall_desert",
    "x": 2082,
    "y": 2,
    "frame_width": 128,
    "frame_height": 128,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "wall_forest",
    "x": 2214,
    "y": 2,
    "frame_width": 128,
    "frame_height": 128,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "wall_ruin",
    "x": 2346,
    "y": 2,
    "frame_width": 128,
    "frame_height": 128,
    "frames": 1,
    "is_animated": false
  },
  {
    "name": "wall_void",
    "x": 2478,
    "y": 2,
    "frame_width": 128,
    "frame_height": 128,
    "frames": 1,
    "is_animated": false
  }
]"#;

impl WorldAtlas {
    pub fn find(&self, name: &str) -> Option<&SpriteMeta> {
        self.sprites.iter().find(|s| s.name == name)
    }
}
